_target_: dyn_ddim.surrogate.backbones.PretrainedBackbone
ckpt_path: "data/models/diffusion/velocity_cos/${seed}/last.ckpt"
times_to_use:
  - 0
  - 50
  - 100
  - 200
  - 400
  - 600
ema: false
untrained: false
