_target_: dyn_ddim.assimilation.EnOIAssimilation
sampler:
  _target_: dyn_ddim.assimilation.CovSampler
  n_ens: 50
  cov_inf: 1.
  covariance:
    - [0.520, 0., 0.]
    - [0., 1.378, 0.]
    - [0., 0., 1.177]
