run:
  dir: data/models/diffusion/${exp_name}

sweep:
  dir: data/models/diffusion
  subdir: ${exp_name}/${hydra.job.num}

output_subdir: hydra

job:
  config:
    override_dirname:
      exclude_keys:
        - exp_name