# @package _global_

defaults:
  - override /hydra/sweeper: optuna
  - override /hydra/sweeper/sampler: grid

hydra:
  mode: "MULTIRUN"
  sweeper:
    _target_: hydra_plugins.hydra_optuna_sweeper.optuna_sweeper.OptunaSweeper
    direction: minimize
    storage: "sqlite:///assim_tuning.sqlite3"
    study_name: ${exp_name}
    n_trials: 100
    n_jobs: 1


dataset_path: "data/raw/traj_train.pt"
n_burn_in: 1000
n_cycles: 5000
seed: 42

logger:
  tags:
    - assimilation
    - tuning