# @package _global_
callbacks:
  model_checkpoint:
    dirpath: 'data/models/diffusion/${exp_name}/${seed}'

hydra:
  mode: "MULTIRUN"
  sweep:
    dir: 'data/models/diffusion'
    subdir: '${exp_name}/${seed}'

  sweeper:
    params:
      seed: 0, 1, 2, 3, 4, 5, 6, 7, 8, 9


output_path: 'data/predictions/diffusion/${exp_name}/${seed}.pt'