# @package _global_


callbacks:
  model_checkpoint:
    dirpath: 'data/models/surrogate_time/${exp_name}/${total.dt}'

hydra:
  mode: "MULTIRUN"
  sweep:
    dir: 'data/models/surrogate_time'
    subdir: '${exp_name}/${total.dt}'

  sweeper:
    params:
      +total: "{dt: '001', nints: 1000},{dt: '002', nints: 500},{dt: '004', nints: 250},{dt: '005', nints: 200},{dt: '020', nints: 50},{dt: '025', nints: 40},{dt: '050', nints: 20},{dt:'100', nints: 10}"


data:
  target: surrogate/surrogate_${total.dt}


n_lead_time: ${total.nints}
output_path: 'data/predictions/surrogate_time/${exp_name}/${total.dt}.pt'