# @package _global_


callbacks:
  model_checkpoint:
    dirpath: 'data/models/surrogate_samples/${exp_name}/${data.n_train_samples}'

hydra:
  mode: "MULTIRUN"
  sweep:
    dir: 'data/models/surrogate_samples'
    subdir: '${exp_name}/${data.n_train_samples}'

  sweeper:
    params:
      data.n_train_samples: 8, 16, 32, 64, 128, 256, 512, 1024, 2048, 4096, 8192, 16384, 32768, 65536, 131072, 262144, 524288, 1048576

output_path: 'data/predictions/surrogate_samples/${exp_name}/${data.n_train_samples}.pt'

trainer:
  max_epochs: -1
  max_steps: 100000
  val_check_interval: 256
  check_val_every_n_epoch: null

data:
  train_batch_size: 64