defaults:
  - logger: wandb
  - assimilation: etkf
  - hydra: default
  - _self_

exp_name: ${now:%Y-%m-%d}_${now:%H-%M-%S}
logging_level: DEBUG
seed: 0
num_workers: 4

obs_every: 10
obs_std: 2
obs_list:
  - 0
  - 1
  - 2

n_ens: 1
n_burn_in: 5000
n_cycles: 50000
dataset_path: "data/raw/traj_test.pt"


hydra:
  run:
    dir: 'data/models/assimilation/${exp_name}'
  sweep:
    dir: data/models/assimilation
    subdir: ${exp_name}/${hydra.job.num}

logger:
  tags:
    - assimilation